### ISSUE TITLE
build-llvm.py not working

### ISSUE THREAD

**Issue by jyizheng** [ClangBuiltLinux/tc-build#113]
```
========================
== Checking CC and LD ==
========================

CC: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang-10
CXX: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++
LD: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/ld.lld

===========================
== Checking dependencies ==
===========================

/usr/local/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/local/bin/ninja

===================
== Updating LLVM ==
===================

Already on 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/llvm/llvm-project
 * branch                    master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.

==============================
== Configuring LLVM stage 1 ==
==============================

-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang-10
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang-10 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++
-- Check for working CXX compiler: /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++ - broken
CMake Error at /usr/local/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/betrfs/llvm-new/tc-build/build/llvm/stage1/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_68162 && [1/2] Building CXX object CMakeFiles/cmTC_68162.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_68162
    FAILED: cmTC_68162 
    : && /home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++   CMakeFiles/cmTC_68162.dir/testCXXCompiler.cxx.o -o cmTC_68162   && :
    /usr/bin/ld: cannot find -lstdc++
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)


-- Configuring incomplete, errors occurred!
See also "/home/betrfs/llvm-new/tc-build/build/llvm/stage1/CMakeFiles/CMakeOutput.log".
See also "/home/betrfs/llvm-new/tc-build/build/llvm/stage1/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "./build-llvm.py", line 1061, in <module>
    main()
  File "./build-llvm.py", line 1057, in main
    do_multistage_build(args, dirs, env_vars)
  File "./build-llvm.py", line 1017, in do_multistage_build
    invoke_cmake(args, dirs, env_vars, stage)
  File "./build-llvm.py", line 902, in invoke_cmake
    subprocess.run(cmake, check=True, cwd=cwd)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Ninja', '-Wno-dev', '-DCLANG_ENABLE_ARCMT=OFF', '-DCLANG_ENABLE_STATIC_ANALYZER=OFF', '-DCLANG_PLUGIN_SUPPORT=OFF', '-DLLVM_BINUTILS_INCDIR=/home/betrfs/llvm-new/tc-build/binutils-2.35/include', '-DLLVM_ENABLE_BINDINGS=OFF', '-DLLVM_ENABLE_PLUGINS=ON', '-DLLVM_ENABLE_OCAMLDOC=OFF', '-DLLVM_ENABLE_TERMINFO=OFF', '-DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR=', '-DLLVM_INCLUDE_DOCS=OFF', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCMAKE_C_COMPILER=/home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang-10', '-DCMAKE_CXX_COMPILER=/home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++', '-DLLVM_USE_LINKER=/home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/ld.lld', '-DLLVM_ENABLE_PROJECTS=clang;lld', '-DLLVM_TARGETS_TO_BUILD=host', '-DLLVM_CCACHE_BUILD=ON', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_ENABLE_BACKTRACES=OFF', '-DLLVM_ENABLE_WARNINGS=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DLLVM_INCLUDE_UTILS=OFF', '-DCLANG_VENDOR=ClangBuiltLinux', '/home/betrfs/llvm-new/tc-build/llvm-project/llvm']' returned non-zero exit status 1.
```

**Comment by msfjarvis** [comment]
The error says that you are using a custom copy of Clang from `/home/betrfs/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04` which is unable to compile a test program because it can't find `libstdc++`. The script is working correctly, it's your compiler that's broken.

**Comment by jyizheng** [comment]
Thanks for your reply. Is libstdc++ the GNU standard c++ library?

**Comment by msfjarvis** [comment]
>  Thanks for your reply. Is libstdc++ the GNU standard c++ library? 

Yes it is.

**Comment by msfjarvis** [comment]
@jyizheng did you resolve your issue?

**Comment by lina-not-linus** [comment]
`[460/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/GlobPatternTest.cpp.o
FAILED: tools/clang/test/CMakeFiles/check-clang 
cd /home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build/llvm/stage1/tools/clang/test && /usr/bin/python /home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build/llvm/stage1/./bin/llvm-lit -sv --param clang_site_config=/home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build/llvm/stage1/tools/clang/test/lit.site.cfg --param USE_Z3_SOLVER=0 /home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build/llvm/stage1/tools/clang/test
[462/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/Host.cpp.o
[463/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/ItaniumManglingCanonicalizerTest.cpp.o
[464/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/ErrorTest.cpp.o
[465/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/KnownBitsTest.cpp.o
[466/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/LEB128Test.cpp.o
[467/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/FormatVariadicTest.cpp.o
[468/572] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/JSONTest.cpp.o
ninja: build stopped: subcommand failed.

========================
== Checking CC and LD ==
========================

CC: /usr/bin/clang-10
CXX: /usr/bin/clang++
LD: /usr/bin/ld.lld

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

===================
== Updating LLVM ==
===================


==============================
== Configuring LLVM stage 1 ==
==============================


===========================
== Building LLVM stage 1 ==
===========================

Traceback (most recent call last):
  File "/home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build-llvm.py", line 1061, in <module>
    main()
  File "/home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build-llvm.py", line 1057, in main
    do_multistage_build(args, dirs, env_vars)
  File "/home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build-llvm.py", line 1018, in do_multistage_build
    invoke_ninja(args, dirs, stage)
  File "/home/shipujin/works/BUILD-llvm-toolchain/arm64-tc-build-5/tc-build/build-llvm.py", line 954, in invoke_ninja
    subprocess.run(['ninja'] +
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', 'check-clang', 'check-lld', 'check-llvm']' returned non-zero exit status 1.
[shipujin@localhost tc-build]$ 
`

**Comment by msfjarvis** [comment]
That's a test failure from the `master` branch, nothing to do with this issue.

Also closing this for inactivity.
