### ISSUE TITLE
Execute build-llvm.py to build a cross toolchain of AArch64

### ISSUE THREAD

**Issue by lina-not-linus** [ClangBuiltLinux/tc-build#125]
**Describe the bug**

```
    Clang :: SemaCXX/large-array-init.cpp          
    Clang :: SemaCXX/warn-unused-local-typedef-serialize.cpp                                                                        
                                 
  Expected Passes    : 15029
  Expected Failures  : 14
  Unsupported Tests  : 1459
  Unexpected Passes  : 2
  Unexpected Failures: 84
[457/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/FileCollectorTest.cpp.o
FAILED: tools/clang/test/CMakeFiles/check-clang 
cd /home/lina/tc-build/build/llvm/stage1/tools/clang/test && /usr/bin/python /home/lina/tc-build/build/llvm/stage1/./bin/llvm-lit -sv --param clang_site_config=/home/lina/tc-build/build/llvm/stage1/tools/clang/test/lit.site.cfg --param USE_Z3_SOLVER=0 /home/lina/tc-build/build/llvm/stage1/tools/clang/test
[459/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/GlobPatternTest.cpp.o
[460/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/Host.cpp.o
[461/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/FileCheckTest.cpp.o
[462/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/ItaniumManglingCanonicalizerTest.cpp.o
[463/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/ErrorTest.cpp.o
[464/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/FormatVariadicTest.cpp.o
[465/573] Building CXX object unittests/Support/CMakeFiles/SupportTests.dir/JSONTest.cpp.o
ninja: build stopped: subcommand failed.

========================
== Checking CC and LD ==
========================

CC: /usr/bin/clang-10
CXX: /usr/bin/clang++
LD: /usr/bin/ld.lld

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

===================
== Updating LLVM ==
===================


==============================
== Configuring LLVM stage 1 ==
==============================


===========================
== Building LLVM stage 1 ==
===========================

Traceback (most recent call last):
  File "./build-llvm.py", line 1061, in <module>
    main()
  File "./build-llvm.py", line 1057, in main
    do_multistage_build(args, dirs, env_vars)
  File "./build-llvm.py", line 1018, in do_multistage_build
    invoke_ninja(args, dirs, stage)
  File "./build-llvm.py", line 954, in invoke_ninja
    subprocess.run(['ninja'] +
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', 'check-clang', 'check-lld', 'check-llvm']' returned non-zero exit status 1.
```

**To Reproduce**

```
./build-llvm.py \
          --assertions \
          --branch "release/10.x" \
          --build-stage1-only \
          --check-targets clang lld llvm \
          --install-stage1-only \
          --projects "clang;lld" \
          --shallow-clone \
          --targets AArch64  2>&1 | tee T-build-llvm.sh.log
```

**Expected behavior**
Execute build-llVm.py to build a cross toolchain of AArch64

**Environment (please complete the following information):**
  - Command you ran: [e.g. `./build-llvm.py`]

```
cat T-build-llvm.sh
#!/bin/bash
set -e
set -x

./build-llvm.py \
          --assertions \
          --branch "release/10.x" \
          --build-stage1-only \
          --check-targets clang lld llvm \
          --install-stage1-only \
          --projects "clang;lld" \
          --shallow-clone \
          --targets AArch64  2>&1 | tee T-build-llvm.sh.log
```

  - Distribution: Fedora32 x86_64
  - Python version: 3.8.2
  - Shell: bash

**Comment by msfjarvis** [comment]
The problem is failing tests and nothing to do with the scripts in the repository. You can skip test execution entirely with this change if you only want the toolchain.

```diff
./build-llvm.py \
          --assertions \
          --branch "release/10.x" \
          --build-stage1-only \
-         --check-targets clang lld llvm \
          --install-stage1-only \
          --projects "clang;lld" \
          --shallow-clone \
          --targets AArch64  2>&1 | tee T-build-llvm.sh.log
```

**Comment by lina-not-linus** [comment]
```
./build-llvm.py \
--assertions \
--branch "release/10.x" \
--build-stage1-only \
--install-stage1-only \
--projects "clang; lld" \
--shallow-clone \
--targets AArch64 2>&1 | tee T-build-llvm.sh.log
```

**The results of**
```
[2820/2820] Linking CXX static library lib/libbenchmark_main.a
ClangBuiltLinux clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

The result is "Target: x86_64-unknown- Linux-gnu" instead of "Aarch64 -unknown- Linux-gnu"
I want to build an AArch64 kernel crossover tool chain

**Comment by lina-not-linus** [comment]
The results of

```
[2820/2820] Linking CXX static library lib/libbenchmark_main.a
ClangBuiltLinux clang version 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
 build an AArch64 kernel crossover tool chain.

This output doesn't seem to be working properly.

Thanks

[T-build-llvm.sh.log-2.txt](https://github.com/ClangBuiltLinux/tc-build/files/5412973/T-build-llvm.sh.log-2.txt)

**Comment by nathanchance** [comment]
> The result is "Target: x86_64-unknown- Linux-gnu" instead of "Aarch64 -unknown- Linux-gnu"
> I want to build an AArch64 kernel crossover tool chain

You have. You are getting confused. The `Target:` line on the output of `clang --version` refers to the host architecture's target, not the list of targets that `clang` can cross compile.

On my `x86_64` host:

```
$ uname -m
x86_64

$ clang --version
ClangBuiltLinux clang version 10.0.1 (https://github.com/llvm/llvm-project ef32c611aa214dea855364efd7ba451ec5ec3f74)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /tmp/tmp.XB5rvfytW4/install/bin
```

On my Raspberry Pi 4:

```
$ uname -m
aarch64

$ /mnt/ssd/toolchains/llvm/bin/clang --version
clang version 12.0.0 (https://github.com/llvm/llvm-project efd02c1548ee458d59063f6393e94e972b5c3d50)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/ssd/toolchains/llvm/bin
```

For what it's worth, all of the tests pass for me when I add `X86` to the list of targets (in other words, change `--targets AArch64` to `--targets "AArch64;X86"`). This is not a problem with the script. You are explicitly not building for your host architecture, which breaks a lot of the assumptions in the LLVM tests apparently. I assume this is because most tests do not pass a `--target=` argument to `clang` so by not having `X86` in the list of targets, you will get a lot of errors along the lines of `error: unable to create target: 'No available targets are compatible with triple "x86_64-unknown-linux-gnu"'`.

Also, why not use `LLVM 11.0.0` at least?
