### ISSUE TITLE
question: how to find out why a linking error happens?

### ISSUE THREAD

**Issue by yEsPaP** [ClangBuiltLinux/tc-build#185]
when it reaches stage 3 somewhere i get an error like this:

```
===========================
== Building LLVM stage 3 ==
===========================

[3010/3596] Linking CXX executable bin/clang-ast-dump
FAILED: bin/clang-ast-dump
: && /mnt/volume_fra1_01/tc_build/build/llvm/stage1/bin/clang++  -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/mnt/volume_fra1_01/tc_build/build/llvm/profdata.prof" -flto=full -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG  -fuse-ld=/mnt/volume_fra1_01/tc_build/build/llvm/stage1/bin/ld.lld -Wl,--color-diagnostics -fprofile-instr-use="/mnt/volume_fra1_01/tc_build/build/llvm/profdata.prof" -flto=full    -Wl,--gc-sections tools/clang/lib/Tooling/DumpTool/CMakeFiles/clang-ast-dump.dir/ASTSrcLocProcessor.cpp.o tools/clang/lib/Tooling/DumpTool/CMakeFiles/clang-ast-dump.dir/ClangSrcLocDump.cpp.o  -o bin/clang-ast-dump  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMOption.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMSupport.a  -lpthread  lib/libclangAST.a  lib/libclangASTMatchers.a  lib/libclangBasic.a  lib/libclangDriver.a  lib/libclangFrontend.a  lib/libclangSerialization.a  lib/libclangToolingCore.a  lib/libclangDriver.a  lib/libLLVMWindowsDriver.a  lib/libLLVMOption.a  lib/libclangParse.a  lib/libclangSema.a  lib/libclangEdit.a  lib/libclangAnalysis.a  lib/libclangASTMatchers.a  lib/libclangAST.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBitReader.a  lib/libLLVMCore.a  lib/libLLVMBinaryFormat.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libclangRewrite.a  lib/libclangLex.a  lib/libclangBasic.a  lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  lib/libLLVMDemangle.a && :
clang-15: error: unable to execute command: Killed
clang-15: error: linker command failed due to signal (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/mnt/volume_fra1_01/tc_build/build-llvm.py", line 1291, in <module>
    main()
  File "/mnt/volume_fra1_01/tc_build/build-llvm.py", line 1287, in main
    do_multistage_build(args, dirs, env_vars)
  File "/mnt/volume_fra1_01/tc_build/build-llvm.py", line 1236, in do_multistage_build
    invoke_ninja(args, dirs, stage)
  File "/mnt/volume_fra1_01/tc_build/build-llvm.py", line 1137, in invoke_ninja
    subprocess.run('ninja', check=True, cwd=build_folder)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ninja' returned non-zero exit status 1.
```

but i don't see what is wrong

building on ubuntu 20.04 , installed https://github.com/ClangBuiltLinux/tc-build/blob/main/ci.sh#L28

**Comment by nathanchance** [comment]
The reason the build failed is `clang-15: error: unable to execute command: Killed`, which means you ran out of memory. I see you are using `--lto=full`, did you read the note in the help text about needing at least 64GB of memory to do a full LTO build? See  #59, #85, and 6cfff5489172544c9fbe9e5ae1ff6047225a8e6b for further information. Use `--lto=thin` if you really want LTO but PGO will give you more gains with less build time.

**Comment by yEsPaP** [comment]
> The reason the build failed is `clang-15: error: unable to execute command: Killed`, which means you ran out of memory. I see you are using `--lto=full`, did you read the note in the help text about needing at least 64GB of memory to do a full LTO build? See #59, #85, and [6cfff54](https://github.com/ClangBuiltLinux/tc-build/commit/6cfff5489172544c9fbe9e5ae1ff6047225a8e6b) for further information. Use `--lto=thin` if you really want LTO but PGO will give you more gains with less build time.

I am using pgo=llvm and lto full. I guess it is because i dont have 64gigs of ram.

Thank you
