### ISSUE TITLE
Build failed on WSL

### ISSUE THREAD

**Issue by wctrl** [ClangBuiltLinux/tc-build#282]
**Describe the bug**
Failed to build final toolchain using latest main branch commit at `SemaExpr.cpp`

**To Reproduce**
1. Run command below
2. Wait
3. See error
```
-- Build files have been written to: /home/user/tc-build/build/llvm/final
$ ninja -C /home/user/tc-build/build/llvm/final all
ninja: Entering directory `/home/user/tc-build/build/llvm/final'
[1923/4344] Building CXX object tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o
FAILED: tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o
/home/user/tc-build/build/llvm/bootstrap/bin/clang++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/user/tc-build/build/llvm/final/tools/clang/lib/Sema -I/home/user/tc-build/src/llvm-project/clang/lib/Sema -I/home/user/tc-build/src/llvm-project/clang/include -I/home/user/tc-build/build/llvm/final/tools/clang/include -I/home/user/tc-build/build/llvm/final/include -I/home/user/tc-build/src/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/home/user/tc-build/build/llvm/instrumented/profdata.prof" -flto=thin -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o -MF tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o.d -o tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaExpr.cpp.o -c /home/user/tc-build/src/llvm-project/clang/lib/Sema/SemaExpr.cpp
[1940/4344] Building CXX object tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaOpenMP.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user/tc-build/build-llvm.py", line 717, in <module>
    final.build()
  File "/home/user/tc-build/tc_build/llvm.py", line 146, in build
    self.run_cmd([*base_ninja_cmd, *self.build_targets])
  File "/home/user/tc-build/tc_build/builder.py", line 39, in run_cmd
    return subprocess.run(cmd, capture_output=capture_output, check=True, cwd=cwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', PosixPath('/home/user/tc-build/build/llvm/final'), 'all']' returned non-zero exit status 1.
```

**Expected behavior**
Successful build

**Environment (please complete the following information):**
  - Command you ran: `python build-llvm.py --lto thin -p clang lld polly --pgo kernel-defconfig  --use-good-revision -t AArch64 ARM X86 --show-build-commands`
  - Distribution: Arch on WSL
  - Python version: 3.12.7
  - Shell: fish
  
Manual invocation `ninja -C /home/user/tc-build/build/llvm/final all` after fail, produces working tc
```
> build/llvm/final/bin/clang --version
ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project 2ab9233f4f393c240c37ef092de09d907fe5c890)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /home/user/tc-build/build/llvm/final/bin
```

**Comment by nathanchance** [comment]
I do not have a machine with WSL and it does not reproduce for me in a fresh Arch Linux `podman` container using your exact command.

```
# /tc-build/build-llvm.py \
--lto thin \
--pgo kernel-defconfig \
--projects clang lld polly \
--quiet-cmake \
--show-build-commands \
--targets AArch64 ARM X86 \
--use-good-revision
...
===================================
== LLVM installation information ==
===================================

Toolchain is available at: /tc-build/build/llvm/final

To use, either run:

        $ export PATH=/tc-build/build/llvm/final/bin:$PATH

or add:

        PATH=/tc-build/build/llvm/final/bin:$PATH

before the command you want to use this toolchain.

ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project 2ab9233f4f393c240c37ef092de09d907fe5c890)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /tc-build/build/llvm/final/bin

ClangBuiltLinux LLD 20.0.0 (https://github.com/llvm/llvm-project 2ab9233f4f393c240c37ef092de09d907fe5c890) (compatible with GNU linkers)

Script duration: 56m 11s
```

**Comment by wctrl** [comment]
Worked with `-t llvmorg-19.1.2` instead of `--use-good-revision`. Probably some WSL issue..
