### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by ikitayama** [ClangBuiltLinux/tc-build#61]
On my reasonably update macOS Mojave I get:

```

-- Performing Test CXX_SUPPORTS_CUSTOM_LINKER
-- Performing Test CXX_SUPPORTS_CUSTOM_LINKER - Failed
CMake Error at cmake/modules/HandleLLVMOptions.cmake:224 (message):
  Host compiler does not support
  '-fuse-ld=/usr/local/Cellar/llvm/9.0.0_1/bin/ld.lld'
Call Stack (most recent call first):
  CMakeLists.txt:656 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/itaru/projects/tc-build/build/llvm/stage1/CMakeFiles/CMakeOutput.log".
See also "/Users/itaru/projects/tc-build/build/llvm/stage1/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "./build-llvm.py", line 890, in <module>
    main()
  File "./build-llvm.py", line 886, in main
    do_multistage_build(args, dirs, env_vars)
  File "./build-llvm.py", line 857, in do_multistage_build
    invoke_cmake(args, dirs, env_vars, stage)
  File "./build-llvm.py", line 753, in invoke_cmake
    subprocess.run(cmake, check=True, cwd=cwd)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Ninja', '-Wno-dev', '-DCLANG_ENABLE_ARCMT=OFF', '-DCLANG_ENABLE_STATIC_ANALYZER=OFF', '-DCLANG_PLUGIN_SUPPORT=OFF', '-DLLVM_BINUTILS_INCDIR=/Users/itaru/projects/tc-build/binutils-2.33.1/include', '-DLLVM_ENABLE_BINDINGS=OFF', '-DLLVM_ENABLE_PLUGINS=ON', '-DLLVM_ENABLE_OCAMLDOC=OFF', '-DLLVM_ENABLE_TERMINFO=OFF', '-DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR=', '-DLLVM_INCLUDE_DOCS=OFF', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCMAKE_C_COMPILER=/usr/local/Cellar/llvm/9.0.0_1/bin/clang-9', '-DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm/9.0.0_1/bin/clang++', '-DLLVM_USE_LINKER=/usr/local/Cellar/llvm/9.0.0_1/bin/ld.lld', '-DLLVM_ENABLE_PROJECTS=clang;lld', '-DLLVM_TARGETS_TO_BUILD=host', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_ENABLE_BACKTRACES=OFF', '-DLLVM_ENABLE_WARNINGS=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DLLVM_INCLUDE_UTILS=OFF', '-DCLANG_VENDOR=ClangBuiltLinux', '/Users/itaru/projects/tc-build/llvm-project/llvm']' returned non-zero exit status 1.
MacBook-Pro:tc-build itaru$
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
  - Command you ran: [e.g. `./build-llvm.py`]
  - Distribution: [e.g. Debian stretch or Arch Linux]
  - Python version: [e.g. 3.7.3]
  - Shell: [e.g. zsh]

**Comment by nathanchance** [comment]
I do not have access to macOS anymore so I am not going to be able to debug this. To be entirely honest, I'm not sure if this is even something that is worth supporting but if someone wants to step up and resolve it, I am fine with it.

**Comment by ikitayama** [comment]
Closing.
